name: Wise Governance
favicon: null
layout_spectrum: 0.68838
typography_spectrum: 0.64875
title: Wise Governance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72902203-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff4e1'
    - '#00acd3'
    - '#005f99'
    - '#521100'
    - '#c84200'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
