typography_spectrum: 0.39785
color:
  brandColors:
    - '#00a8e5'
    - '#ddf2f2'
    - '#030301'
    - '#ff8200'
    - '#7c340b'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25363
analytics:
  google: UA-72902203-1
  facebook: null
  twitter: null
name: Wise Governance
cta:
  domain: null
  bucket: null
  version: null
navigation: []
favicon: null
title: Wise Governance
description: 'Education, Compliance, Referral'
purpose: []
