typography_spectrum: 0.39785
color:
  brandColors:
    - '#00a8e5'
    - '#ddf2f2'
    - '#030301'
    - '#ff8200'
    - '#7c340b'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25363
analytics:
  google: UA-72902203-1
  facebook: null
  twitter: null
name: Wise Governance
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Education
    id: c4d5e0f6-aae9-43b6-97f1-079b41bcbb18
    type: content
  - name: 'Compliance '
    id: 61ba8977-87a6-44de-9192-208ec9823c42
    type: content
  - name: Referral
    id: c50e2aeb-b395-494a-8319-dd2b6b3bda65
    type: content
  - name: About
    id: 0b7202eb-ba8e-44de-95a6-b372b492a196
    type: content
favicon: null
title: Wise Governance
description: 'Education, Compliance, Referral'
purpose: []
