name: Wise Governance
favicon: null
layout_spectrum: 0.61214
typography_spectrum: 0.64875
title: Wise Governance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72902203-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff9700'
    - '#03a9f5'
    - '#4cb050'
    - '#666666'
  brandStrength: 1
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 1
purpose: []
