name: Wise Governance
favicon: null
layout_spectrum: 0.36462
typography_spectrum: 0.39785
title: Wise Governance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72902203-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00a8e5'
    - '#ddf2f2'
    - '#030301'
    - '#ff8200'
    - '#7c340b'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
