name: Wise Governance
favicon: null
layout_spectrum: 0.24535
typography_spectrum: 0.15411531436257064
title: Wise Governance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfbb8c'
    - '#150e0a'
    - '#3f392a'
    - '#85785c'
    - '#675c44'
  brandStrength: 0.31798018934205174
  lightness: 0.4532455357257277
  saturation: 0.5625
  rhythmicContrast: 0.18386868224479258
purpose: []
