name: Wise Governance
favicon: null
layout_spectrum: 0.78886
typography_spectrum: 0.15411531436257064
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ff7d0c'
    - '#ffffff'
    - '#634411'
    - '#ff0000'
  brandStrength: 0.31798018934205174
  lightness: 0.4532455357257277
  saturation: 0.5625
  rhythmicContrast: 0.18386868224479258
purpose: []
