name: Wise Governance
favicon: null
layout_spectrum: 0.35679
typography_spectrum: 0.64875
title: Wise Governance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72902203-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff4e1'
    - '#00acd3'
    - '#005f99'
    - '#521100'
    - '#c84200'
  brandStrength: 0.31798018934205174
  lightness: 0.4532455357257277
  saturation: 0.5625
  rhythmicContrast: 0.18386868224479258
purpose: []
